# Generated by Django 4.1.5 on 2023-01-19 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='Registrations',
        ),
    ]
