# Generated by Django 4.1.5 on 2023-01-19 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0002_rename_registration_registrations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registrations',
            new_name='Registration',
        ),
    ]
