# Generated by Django 4.1.5 on 2023-01-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0003_rename_registrations_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
