# Generated by Django 4.1.5 on 2023-01-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studapp', '0004_delete_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=100)),
                ('a_address', models.CharField(max_length=100)),
                ('a_type', models.CharField(max_length=100)),
                ('a_fecility', models.TextField()),
                ('a_rent', models.CharField(max_length=100)),
                ('a_photo1', models.FileField(upload_to='documents/%Y%m%d/')),
                ('a_photo3', models.FileField(upload_to='documents/%Y%m%d/')),
                ('date', models.DateField()),
            ],
        ),
    ]
