# Generated by Django 4.1.5 on 2023-01-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='a_photo1',
            field=models.FileField(upload_to='static/documents/'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='a_photo3',
            field=models.FileField(upload_to='static/documents/'),
        ),
    ]
